const staminaSkills = [
  { name: "Introduction to Physiology", type: "stamina" },
  { name: "Clear Heart", type: "stamina" },
  { name: "Super-Duper Stoked", type: "stamina" },
  { name: "U=ma2", type: "stamina" },
  { name: "Pure Heart", type: "stamina" },
  { name: "Super-Duper Climax", type: "stamina" },
  { name: "Swinging Maestro", type: "stamina" },
  { name: "Corner Recovery ○", type: "stamina" },
  { name: "Breath of Fresh Air", type: "stamina" },
  { name: "Straightaway Recovery", type: "stamina" },
  { name: "Iron Will", type: "stamina" },
  { name: "Lay Low", type: "stamina" },
  { name: "Indomitable", type: "stamina" },
  { name: "Pace Strategy", type: "stamina" },
  { name: "Unruffled", type: "stamina" },
  { name: "Calm in a Crowd", type: "stamina" },
  { name: "Calm and Collected", type: "stamina" },
  { name: "Stamina to Spare", type: "stamina" },
  { name: "Race Planner", type: "stamina" },
  { name: "Preferred Position", type: "stamina" },
  { name: "Sleeping Lion", type: "stamina" },
  { name: "Standing By", type: "stamina" },
  { name: "Wait-and-See", type: "stamina" },
  { name: "Keen Eye", type: "stamina" },
  { name: "Watchful Eye", type: "stamina" },
  { name: "Trackblazer", type: "stamina" },
  { name: "Rosy Outlook", type: "stamina" },
  { name: "Cooldown", type: "stamina" },
  { name: "Deep Breaths", type: "stamina" },
  { name: "Adrenaline Rush", type: "stamina" },
  { name: "Extra Tank", type: "stamina" },
  { name: "Miraculous Step", type: "stamina" },
  { name: "Soft Step", type: "stamina" },
  { name: "Passing Pro", type: "stamina" },
  { name: "Restless", type: "stamina" },
  { name: "Moxie", type: "stamina" },
  { name: "Gourmand", type: "stamina" },
  { name: "Hydrate", type: "stamina" },
  { name: "Relax", type: "stamina" },
  { name: "A Small Breather", type: "stamina" },
  { name: "Go-Home Specialist", type: "stamina" },
  { name: "After-School Stroll", type: "stamina" },
  { name: "Serenity", type: "stamina" },
  { name: "Levelheaded", type: "stamina" },
  { name: "Triple 7s", type: "stamina" },
  { name: "Shake It Out", type: "stamina" },
  { name: "Superior Heal", type: "stamina" },
  { name: "Dazzl'n ♪ Diver", type: "stamina" }
];

const speedSkills = [
  { name: "Corner Adept ○", type: "speed" },
  { name: "Straightaway Adept", type: "speed" },
  { name: "Ramp Up", type: "speed" },
  { name: "Homestretch Haste", type: "speed" },
  { name: "Fast-Paced", type: "speed" },
  { name: "Prepared to Pass", type: "speed" },
  { name: "Position Pilfer", type: "speed" },
  { name: "Outer Swell", type: "speed" },
  { name: "Masterful Gambit", type: "speed" },
  { name: "Gap Closer", type: "speed" },
  { name: "Productive Plan", type: "speed" },
  { name: "Up-Tempo", type: "speed" },
  { name: "Steadfast", type: "speed" },
  { name: "Inside Scoop", type: "speed" },
  { name: "Sprint Straightaways ◎", type: "speed" },
  { name: "Sprint Straightaways ○", type: "speed" },
  { name: "Sprint Corners ◎", type: "speed" },
  { name: "Sprint Corners ○", type: "speed" },
  { name: "Huge Lead", type: "speed" },
  { name: "Mile Straightaways ◎", type: "speed" },
  { name: "Mile Straightaways ○", type: "speed" },
  { name: "Mile Corners ◎", type: "speed" },
  { name: "Mile Corners ○", type: "speed" },
  { name: "Shifting Gears", type: "speed" },
  { name: "Unyielding Spirit", type: "speed" },
  { name: "Medium Straightaways ◎", type: "speed" },
  { name: "Medium Straightaways ○", type: "speed" },
  { name: "Medium Corners ◎", type: "speed" },
  { name: "Medium Corners ○", type: "speed" },
  { name: "Long Straightaways ◎", type: "speed" },
  { name: "Long Straightaways ○", type: "speed" },
  { name: "Long Corners ◎", type: "speed" },
  { name: "Long Corners ○", type: "speed" },
  { name: "Keeping the Lead", type: "speed" },
  { name: "Pressure", type: "speed" },
  { name: "Front Runner Straightaways ◎", type: "speed" },
  { name: "Front Runner Straightaways ○", type: "speed" },
  { name: "Front Runner Corners ◎", type: "speed" },
  { name: "Front Runner Corners ○", type: "speed" },
  { name: "Leader's Pride", type: "speed" },
  { name: "Pace Chaser Straightaways ◎", type: "speed" },
  { name: "Pace Chaser Straightaways ○", type: "speed" },
  { name: "Pace Chaser Corners ◎", type: "speed" },
  { name: "Pace Chaser Corners ○", type: "speed" },
  { name: "Late Surger Straightaways ◎", type: "speed" },
  { name: "Late Surger Straightaways ○", type: "speed" },
  { name: "Late Surger Corners ◎", type: "speed" },
  { name: "Late Surger Corners ○", type: "speed" },
  { name: "1,500,000 CC", type: "speed" },
  { name: "End Closer Straightaways ◎", type: "speed" },
  { name: "End Closer Straightaways ○", type: "speed" },
  { name: "End Closer Corners ◎", type: "speed" },
  { name: "End Closer Corners ○", type: "speed" },
  { name: "Uma Stan", type: "speed" },
  { name: "Tail Held High", type: "speed" },
  { name: "Slipstream", type: "speed" },
  { name: "Playtime's Over!", type: "speed" },
  { name: "Top Pick", type: "speed" },
  { name: "Professor of Curvature", type: "speed" },
  { name: "Beeline Burst", type: "speed" },
  { name: "It's On!", type: "speed" },
  { name: "In Body and Mind", type: "speed" },
  { name: "Escape Artist", type: "speed" },
  { name: "Speed Star", type: "speed" },
  { name: "Fast & Furious", type: "speed" },
  { name: "Rising Dragon", type: "speed" },
  { name: "Sturm und Drang", type: "speed" },
  { name: "Blinding Flash", type: "speed" },
  { name: "Mile Maven", type: "speed" },
  { name: "Killer Tunes", type: "speed" },
  { name: "Unyielding", type: "speed" },
  { name: "Innate Experience", type: "speed" },
  { name: "Staggering Lead", type: "speed" },
  { name: "Changing Gears", type: "speed" },
  { name: "Big-Sisterly", type: "speed" },
  { name: "Vanguard Spirit", type: "speed" },
  { name: "Overwhelming Pressure", type: "speed" },
  { name: "15,000,000 CC", type: "speed" },
  { name: "Trending in the Charts!", type: "speed" },
  { name: "Certain Victory", type: "speed" },
  { name: "Legacy of the Strong", type: "speed" },
  { name: "Warning Shot!", type: "speed" },
  { name: "Xceleration", type: "speed" },
  { name: "Red Ace", type: "speed" },
  { name: "Focused Mind", type: "speed" },
  { name: "Corazón ☆ Ardiente", type: "speed" },
  { name: "Empress's Pride", type: "speed" },
  { name: "1st Place Kiss☆", type: "speed" },
  { name: "V Is for Victory!", type: "speed" },
  { name: "Class Rep + Speed = Bakushin", type: "speed" },
  { name: "Luck Be with Me!", type: "speed" },
  { name: "I Can Win Sometimes, Right?", type: "speed" },
  { name: "Call Me King", type: "speed" },
  { name: "Shooting Star", type: "speed" },
  { name: "The View from the Lead Is Mine!", type: "speed" },
  { name: "Sky-High Teio Step", type: "speed" },
  { name: "Triumphant Pulse", type: "speed" },
  { name: "Anchors Aweigh!", type: "speed" },
  { name: "Cut and Drive!", type: "speed" },
  { name: "Resplendent Red Ace", type: "speed" },
  { name: "Where There's a Will, There's a Way", type: "speed" },
  { name: "The Duty of Dignity Calls", type: "speed" },
  { name: "Victoria por plancha ☆", type: "speed" },
  { name: "This Dance Is for Vittoria!", type: "speed" },
  { name: "Behold Thine Emperor's Divine Might", type: "speed" },
  { name: "Blazing Pride", type: "speed" },
  { name: "∴win Q.E.D.", type: "speed" },
  { name: "Flashy☆Landing", type: "speed" },
  { name: "G00 1st. F∞;", type: "speed" },
  { name: "Blue Rose Closer", type: "speed" },
  { name: "Our Ticket to Win!", type: "speed" },
  { name: "Genius x Bakushin = Victory", type: "speed" },
  { name: "I See Victory in My Future!", type: "speed" },
  { name: "Just a Little Farther!", type: "speed" },
  { name: "Prideful King", type: "speed" },
  { name: "#LookatCurren", type: "speed" },
  { name: "Nemesis", type: "speed" },
  { name: "SPARKLY☆STARDOM", type: "speed" },
  { name: "Shadow Break", type: "speed" },
  { name: "Eternal Moments", type: "speed" },
  { name: "Flowery☆Maneuver", type: "speed" },
  { name: "You and Me! One-on-One!", type: "speed" },
  { name: "Lights of Vaudeville", type: "speed" },
  { name: "KEEP IT REAL.", type: "speed" },
  { name: "A Kiss for Courage", type: "speed" },
  { name: "I Never Goof Up!", type: "speed" },
  { name: "Schwarzes Schwert", type: "speed" },
  { name: "Bountiful Harvest", type: "speed" },
  { name: "Corner Acceleration ○", type: "speed" },
  { name: "Straightaway Acceleration", type: "speed" },
  { name: "Nimble Navigator", type: "speed" },
  { name: "Early Lead", type: "speed" },
  { name: "Final Push", type: "speed" },
  { name: "Slick Surge", type: "speed" },
  { name: "Straightaway Spurt", type: "speed" },
  { name: "Sprinting Gear", type: "speed" },
  { name: "Updrafters", type: "speed" },
  { name: "Countermeasure", type: "speed" },
  { name: "Acceleration", type: "speed" },
  { name: "Second Wind", type: "speed" },
  { name: "Shrewd Step", type: "speed" },
  { name: "Straight Descent", type: "speed" },
  { name: "Tactical Tweak", type: "speed" },
  { name: "Fighter", type: "speed" },
  { name: "Highlander", type: "speed" },
  { name: "Groundwork", type: "speed" },
  { name: "Corner Connoisseur", type: "speed" },
  { name: "Rushing Gale!", type: "speed" },
  { name: "No Stopping Me!", type: "speed" },
  { name: "Taking the Lead", type: "speed" },
  { name: "Unrestrained", type: "speed" },
  { name: "On Your Left!", type: "speed" },
  { name: "Encroaching Shadow", type: "speed" },
  { name: "Turbo Sprint", type: "speed" },
  { name: "Furious Feat", type: "speed" },
  { name: "Plan X", type: "speed" },
  { name: "Step on the Gas!", type: "speed" },
  { name: "Reignition", type: "speed" },
  { name: "Technician", type: "speed" },
  { name: "Determined Descent", type: "speed" },
  { name: "Shatterproof", type: "speed" },
  { name: "Hard Worker", type: "speed" },
  { name: "Feel the Burn!", type: "speed" },
  { name: "Red Shift/LP1211-M", type: "speed" },
  { name: "Shooting for Victory!", type: "speed" },
  { name: "Let's Pump Some Iron!", type: "speed" },
  { name: "Angling and Scheming", type: "speed" },
  { name: "Condor's Fury", type: "speed" }
];

const debuffSkills = [
  { name: "Hesitant Front Runners", type: "debuff" },
  { name: "Hesitant Pace Chasers", type: "debuff" },
  { name: "Hesitant Late Surgers", type: "debuff" },
  { name: "Hesitant End Closers", type: "debuff" },
  { name: "Intimidate", type: "debuff" },
  { name: "Speed Eater", type: "debuff" },
  { name: "Tether", type: "debuff" },
  { name: "Intense Gaze", type: "debuff" },
  { name: "Greed for Speed", type: "debuff" },
  { name: "Dominator", type: "debuff" },
  { name: "Petrifying Gaze", type: "debuff" },
  { name: "Adored by All", type: "debuff" },
  { name: "Opening Gambit", type: "debuff" },
  { name: "Restart", type: "debuff" },
  { name: "Battle Formation", type: "debuff" },
  { name: "Frenzied Front Runners", type: "debuff" },
  { name: "Frenzied Pace Chasers", type: "debuff" },
  { name: "Frenzied Late Surgers", type: "debuff" },
  { name: "Frenzied End Closers", type: "debuff" },
  { name: "Trick (Front)", type: "debuff" },
  { name: "Trick (Rear)", type: "debuff" },
  { name: "Subdued Front Runners", type: "debuff" },
  { name: "Flustered Front Runners", type: "debuff" },
  { name: "Subdued Pace Chasers", type: "debuff" },
  { name: "Flustered Pace Chasers", type: "debuff" },
  { name: "Subdued Late Surgers", type: "debuff" },
  { name: "Flustered Late Surgers", type: "debuff" },
  { name: "Subdued End Closers", type: "debuff" },
  { name: "Flustered End Closers", type: "debuff" },
  { name: "Stop Right There!", type: "debuff" },
  { name: "Murmur", type: "debuff" },
  { name: "Stamina Eater", type: "debuff" },
  { name: "Sharp Gaze", type: "debuff" },
  { name: "You've Got No Shot", type: "debuff" },
  { name: "Mystifying Murmur", type: "debuff" },
  { name: "Stamina Siphon", type: "debuff" },
  { name: "All-Seeing Eyes", type: "debuff" },
  { name: "Smoke Screen", type: "debuff" },
  { name: "Disorient", type: "debuff" },
  { name: "Illusionist", type: "debuff" },
  { name: "Dazzling Disorientation", type: "debuff" }
];

const greenSkills = [
  { name: "Right-Handed ◎", type: "green" },
  { name: "Right-Handed ○", type: "green" },
  { name: "Left-Handed ◎", type: "green" },
  { name: "Left-Handed ○", type: "green" },
  { name: "Spring Runner ◎", type: "green" },
  { name: "Spring Runner ○", type: "green" },
  { name: "Summer Runner ◎", type: "green" },
  { name: "Summer Runner ○", type: "green" },
  { name: "Fall Runner ◎", type: "green" },
  { name: "Fall Runner ○", type: "green" },
  { name: "Winter Runner ◎", type: "green" },
  { name: "Winter Runner ○", type: "green" },
  { name: "Outer Post Proficiency ◎", type: "green" },
  { name: "Outer Post Proficiency ○", type: "green" },
  { name: "Maverick ◎", type: "green" },
  { name: "Maverick ○", type: "green" },
  { name: "Long Shot ◎", type: "green" },
  { name: "Long Shot ○", type: "green" },
  { name: "Sympathy", type: "green" },
  { name: "Lone Wolf", type: "green" },
  { name: "Unchanging", type: "green" },
  { name: "Tokyo Racecourse ◎", type: "green" },
  { name: "Tokyo Racecourse ○", type: "green" },
  { name: "Nakayama Racecourse ◎", type: "green" },
  { name: "Nakayama Racecourse ○", type: "green" },
  { name: "Hanshin Racecourse ◎", type: "green" },
  { name: "Hanshin Racecourse ○", type: "green" },
  { name: "Kyoto Racecourse ◎", type: "green" },
  { name: "Kyoto Racecourse ○", type: "green" },
  { name: "Chukyo Racecourse ◎", type: "green" },
  { name: "Chukyo Racecourse ○", type: "green" },
  { name: "Sapporo Racecourse ◎", type: "green" },
  { name: "Sapporo Racecourse ○", type: "green" },
  { name: "Hakodate Racecourse ◎", type: "green" },
  { name: "Hakodate Racecourse ○", type: "green" },
  { name: "Fukushima Racecourse ◎", type: "green" },
  { name: "Fukushima Racecourse ○", type: "green" },
  { name: "Niigata Racecourse ◎", type: "green" },
  { name: "Niigata Racecourse ○", type: "green" },
  { name: "Kokura Racecourse ◎", type: "green" },
  { name: "Kokura Racecourse ○", type: "green" },
  { name: "Standard Distance ◎", type: "green" },
  { name: "Standard Distance ○", type: "green" },
  { name: "Non-Standard Distance ◎", type: "green" },
  { name: "Non-Standard Distance ○", type: "green" },
  { name: "Oi Racecourse ◎", type: "green" },
  { name: "Oi Racecourse ○", type: "green" },
  { name: "Firm Conditions ◎", type: "green" },
  { name: "Firm Conditions ○", type: "green" },
  { name: "Wet Conditions ◎", type: "green" },
  { name: "Wet Conditions ○", type: "green" },
  { name: "Competitive Spirit ◎", type: "green" },
  { name: "Competitive Spirit ○", type: "green" },
  { name: "Sunny Days ◎", type: "green" },
  { name: "Sunny Days ○", type: "green" },
  { name: "Cloudy Days ◎", type: "green" },
  { name: "Cloudy Days ○", type: "green" },
  { name: "Rainy Days ◎", type: "green" },
  { name: "Rainy Days ○", type: "green" },
  { name: "Snowy Days ◎", type: "green" },
  { name: "Snowy Days ○", type: "green" },
  { name: "Target in Sight ◎", type: "green" },
  { name: "Target in Sight ○", type: "green" },
  { name: "Inner Post Proficiency ◎", type: "green" },
  { name: "Inner Post Proficiency ○", type: "green" },
  { name: "Front Runner Savvy ◎", type: "green" },
  { name: "Front Runner Savvy ○", type: "green" },
  { name: "Pace Chaser Savvy ◎", type: "green" },
  { name: "Pace Chaser Savvy ○", type: "green" },
  { name: "Late Surger Savvy ◎", type: "green" },
  { name: "Late Surger Savvy ○", type: "green" },
  { name: "End Closer Savvy ◎", type: "green" },
  { name: "End Closer Savvy ○", type: "green" },
  { name: "Lucky Seven", type: "green" },
  { name: "Super Lucky Seven", type: "green" }
];